=== Mirul3089/Xml-and-Js/week-4/index.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ps [
    <!ELEMENT ps (product+)>
    <!ELEMENT product (pName, Sizes, prices)>
    <!ATTLIST product id ID #REQUIRED>
    <!ELEMENT pName (#PCDATA)>
    <!ELEMENT Sizes (size+)>
    <!ATTLIST size description CDATA #REQUIRED>
    <!ELEMENT size (#PCDATA)>
    <!ELEMENT prices (price+)>
    <!ATTLIST price currency CDATA #REQUIRED>
    <!ELEMENT price (#PCDATA)>
]>

=== Mirul3089/Xml-and-Js/week-4/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "index.dtd">
<!DOCTYPE products SYSTEM "index.xsd">
<ps>
    <product id="a332d8d2-86d7-11ec-a8a3-0242ac120002">
        <pName>Microfleece hoodie</pName>
        <Sizes>
            <size description="xs">0 items</size>
            <size description="s">3 items</size>
            <size description="m">13 items</size>
            <size description="l">5 items</size>
            <size description="xl">2 items</size>
        </Sizes>
        <prices>
            <price currency="USD">USD&#36;49.99</price>
            <price currency="CAD">CAD&#36;59.99</price>
        </prices>
    </product>
    <product id="a332dac6-86d7-11ec-a8a3-0242ac120002">
        <pName>Vintage Soft Hoodie</pName>
        <Sizes>
            <size description="xs">3 items</size>
            <size description="s">8 items</size>
            <size description="m">25 items</size>
            <size description="l">12 items</size>
            <size description="xl">4 items</size>
        </Sizes>
        <prices>
            <price currency="USD">USD&#36;39.99</price>
            <price currency="CAD">CAD&#36;49.99</price>
        </prices>
    </product>
    <product id="a332dbf2-86d7-11ec-a8a3-0242ac120002">
        <pName>Crewneck Sweatshirt</pName>
        <Sizes>
            <size description="xs">0 items</size>
            <size description="s">0 items</size>
            <size description="m">15 items</size>
            <size description="l">13 items</size>
            <size description="xl">0 items</size>
        </Sizes>
        <prices>
            <price currency="CAD">CAD&#36;47.97</price>
        </prices>
    </product>
    <product id="a332dd0a-86d7-11ec-a8a3-0242ac120002">
        <pName>French Terry Raglan Crewneck Sweatshirt</pName>
        <Sizes>
            <size description="xs">0 items</size>
            <size description="s">0 items</size>
            <size description="m">0 items</size>
            <size description="l">1 items</size>
            <size description="xl">0 items</size>
        </Sizes>
        <prices>
            <price currency="USD">USD&#36;37.97</price>
        </prices>
    </product>
</ps>
